# -*- coding: utf-8 -*-
"""Copy of Prince_George_Personas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBlgGo1EMgWL1H2c8CB0t3HJh3NVpgIV

Imports
"""

import numpy as np
import pandas as pd
import io

!pip install scipy

from numpy import vstack,array
from numpy.random import rand
from scipy.cluster.vq import kmeans,vq,whiten
from sklearn.datasets import load_digits
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

"""Load data"""

from google.colab import files
 
 
uploaded = files.upload()

df = pd.read_csv(io.BytesIO(uploaded['PG - survey and votes - clean.csv']))
df.head(3)

df.shape
df.describe()

# Additional Data Cleaning
df["Email"].unique() # email is meaningless

df.drop(columns = ["Influence", "Email", "Civility Pledge", "Civility Pledge: Yes, I agree"], inplace = True)

# fill nan with 0 (might have been the wrong thing to do)
df = df._get_numeric_data().fillna(0)
df.describe()

#what are we trying to predict by 
# Personas types of person

#PCA

pca = PCA(n_components = 5)
pca.fit(df)
transform_df = pca.transform(df)



kmeans = KMeans(n_clusters= 5)
label = kmeans.fit_predict(transform_df)
#print(label)
#transform_df["label"] = label
print(pd.DataFrame(transform_df))

# Data is not clean because we get the same PCA value for each of the first 5 labels

# Do we actually need to know what each column is (do we need to know predictors?)

dir(kmeans)

kmeans.cluster_centers_.shape

df.columns
print(u_labels)

#Plotting

 
u_labels = np.unique(label)

# This is where it goes wrong
for i in u_labels:
   temp_df = transform_df[transform_df["label"] == i]
   plt.scatter(temp_df["Satisfaction  Roads and Sidewalks Services"] , temp_df["Satisfaction Community Support services"])
   print(temp_df)
   


#plt.legend()
#plt.show()

"""I used these websites 

https://www.askpython.com/python/examples/plot-k-means-clusters-python

https://medium.com/@blazetamareborn/practicing-clustering-techniques-on-survey-dataset-f7d7a322e6ff
"""